### ISSUE TITLE
 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Zhou2019** [NUS-HPC-AI-Lab/InfoBatch#20]
Has the author ever encountered Segmentation fault (core dumped)? There will be no problem when num_workers = 0, but it will occur with a certain probability when num_workers>0, which I think is the reason for multiple processes. InfoBatch works well when num_worker>0, but I need to modify it to suit my task. There is no other error message for the problem, which makes it difficult for me to debug him.
Does the author have a solution that can be consulted?

**Comment by henryqin1997** [comment]
Thank you for your update👍🏻. We will update our code on this part.
